configurations: []
executionInputs: []
triggers: []
steps:
  - params:
      - name: COMMANDS
        code: false
        value: echo pipeline05BS
      - name: finishSignal
        code: false
        value: exit
      - name: shell
        code: false
        value: default
      - name: workingDir
        code: false
        value: null
    type: plugin
    id: CommandLine2
    displayName: Command Line pipeline05BSCMD
    description: '1'
    timeout: null
    agent: null
    retries: null
    plugin: CommandLine@3.2.1
    pluginAccount: null
    method: execute
    nextStep: CommandLine1
  - params:
      - name: COMMANDS
        code: false
        value: sleep20
      - name: finishSignal
        code: false
        value: exit
      - name: shell
        code: false
        value: default
      - name: workingDir
        code: false
        value: null
    type: plugin
    id: CommandLine1
    displayName: Command Line
    timeout: null
    agent: null
    retries: null
    plugin: CommandLine@3.2.1
    pluginAccount: null
    method: execute
    nextStep: null
kaholoVersion: 6.2.0
name: pipeline05Desc
description: ''
agent: null
timeout: null
maxConcurrency: 1
firstStep: CommandLine2
