configurations: []
executionInputs: []
triggers:
  - name: '3'
    type: plugin
    description: '3'
    plugin: gitops
    configuration: null
    method: push-branch
    params:
      - name: branches
        value: null
      - name: branchesIgnore
        value: null
steps:
  - params:
      - name: COMMANDS
        code: false
        value: sleep 15
      - name: finishSignal
        code: false
        value: exit
      - name: shell
        code: false
        value: default
      - name: workingDir
        code: false
        value: null
    type: plugin
    id: CommandLine1
    displayName: Command Line
    description: '12333'
    timeout: null
    agent: null
    retries: null
    plugin: CommandLine@3.2.1
    pluginAccount: null
    method: execute
    nextStep: null
kaholoVersion: 6.2.0
name: pipeline03
description: '1'
agent:
  type: dynamic
  name: agent-php
  size: small
timeout: ''
maxConcurrency: 1
firstStep: CommandLine1
